
ANTHROPIC_API_KEY = "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"

[auth]
redirect_uri = "https://your-app-name.streamlit.app/oauth2callback"
cookie_secret = "storable-qa-super-secret-cookie-2024"

[auth.google]
client_id = "152683404273-e7vcv5his4ghbcom0ik236krqaueo44m.apps.googleusercontent.com"
client_secret = "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"
